package com.telehop.common.model;

public enum PacketType {
    PING,
    PLAYER_SERVER_UPDATE,
    TRANSFER_PLAYER,
    EXECUTE_POST_JOIN_TELEPORT,
    TPA_CREATE,
    TPA_CANCEL,
    TPA_ACCEPT,
    TPA_DENY,
    TPA_TIMEOUT,
    PLAYER_LIST_REQUEST,
    PLAYER_LIST_RESPONSE,
    WARP_TELEPORT,
    WARP_CREATE,
    WARP_DELETE,
    WARP_LIST,
    PWARP_TELEPORT,
    RTP_REQUEST,
    SPAWN_REQUEST,
    TELEPORT_TO_PLAYER,
    ADMIN_TP_REQUEST,
    RESPONSE,
    ERROR
}
